- name: Initialize elem list
  set_fact:
    new_list: []
    new_ro: []

- name: Loop through first entry groups
  include_tasks: els.yml
  loop: "{{ cgn.list }}"
  loop_control:
    loop_var: elem
  when: "'list' in cgn"

- name: Pull secondary cgn
  ansible.builtin.set_fact:
    cgn2_idx: "{{ lookup('ansible.utils.index_of', cust_2, 'eq', '{{ cgn.name }}', 'name') }}"

- name: DEBUGGING {{ cgn.name }}
  debug:
    msg: "{{ cgn2_idx }}"

- name: Loop through second entry groups
  include_tasks: els.yml
  loop: "{{ cust_2[cgn2_idx | int].list }}"
  loop_control:
    loop_var: elem
  when: cgn2_idx | length > 0

- name: Pull second entry rules
  set_fact:
    new_ro: "{{ cust_2[cgn2_idx | int].ro }}"
  when:
    - cgn2_idx | length > 0
    - "'ro' in cust_2[cgn2_idx | int]"

- name: Remove cgn from secondary list
  set_fact:
    cust_2: "{{ cust_2 | difference([cust_2[cgn2_idx | int]]) }}"
  when: cgn2_idx | length > 0

- name: Set new cgn
  set_fact:
    new_cgn:
      name: "{{ cgn.name }}"
      list: "{{ new_list }}"
      ro: "{{ new_ro }}"

- name: Add cgn to full
  set_fact:
    full: "{{ full + [ new_cgn ] }}"