- name: Initialize full variable
  set_fact:
    full: []

- name: Volatile variable for second file
  set_fact:
    cust_2: "{{ cust }}"

- name: DEBUGGING
  debug:
    msg: "{{ cust_2 }}"

- name: Loop through first list
  include_tasks: cgns.yml
  loop: "{{ uni }}"
  loop_control:
    loop_var: cgn

- name: Add remaining second list
  set_fact:
    full: "{{ full + cust_2 }}"