- name: Item value
  debug:
    msg: "{{ item }}"

- name: Item value - name
  debug:
    msg: "{{ item.name }}"

- name: Item value - a
  debug:
    msg: "{{ item.a }}"

- name: Item value - b
  debug:
    msg: "{{ item.b }}"