- name: Getting value for...
  debug:
    msg: "{{ item.key }}"
  
- block:
  - name: Set temp var
    set_fact:
      temp_test:
          j: "{{ item.value.j }}"
          i: "{{ my_idx }}"


  - name: Update dict
    set_fact:
      test: "{{ test | combine( { {{ item.key }}: temp_test } ) }}"

#  - name: Get from Other
#    set_fact:
#      test: "{{ test | combine( { {{ item.key }}: my_idx } ) }}"


  when: "'{{ item.value.i }}' == ''"

- name: Get from Dictionary
  set_fact:
    cluster_ip: "{{ test[item.key] }}"

- name: New Value
  debug:
    msg: "{{ test }}"