- name: Testing for EJ
  hosts: localhost
  vars:
    tmp:
      - "qwer 8520"
      - "zxcv 13974"
  tasks:
    - name: join test
      copy:
        dest: "tst.txt"
        content: "{{ tmp | join('\n') }}"