- name: Testing for EJ
  hosts: localhost
  tasks:
    - name: wget from GitHub
      get_url:
        url: https://github.com/Batophobia/AoC/archive/refs/heads/master.zip
        dest: ./
    - name: Unzip
      unarchive:
        src: AoC-master.zip
        dest: ./