- name: Testing for EJ
  hosts: localhost
  tasks:
    - name: Touch test
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "bip": "10.10.10.1/24"
          }