- name: Testing for EJ
  hosts: localhost
  tasks:
    - name: Wait test
      wait_for: 
        port: 22
        host: "{{ item }}"
      loop:
        - 172.17.0.2
        - 172.17.0.3
    - name: After wait
      debug:
        msg: Wait ended