- name: Testing for EJ
  hosts: localhost
  vars:
    keys:
      - key1
      - key2
      - key3
      - key4
  tasks:
    - name: object loop
      debug:
        msg: "{{ loop_idx + 1 }} - {{ item }}"
      loop: "{{ keys }}"
      loop_control:
        index_var: loop_idx