- name: Testing for EJ
  hosts: localhost
  vars_prompt:
    - name: test_var
      prompt: Enter Value
  environment:
    ENV_VAR: "{{ test_var }}"
  vars:
    val: "{{ test_var }}"
  tasks:
  - name: val test (works)
    debug:
      msg: "{{ val }}"
  - name: ENV_VAR test (breaks)
    debug:
      msg: "{{ ENV_VAR }}"