- name: Testing for EJ
  hosts: localhost
  vars:
    val: boi
  tasks:
  - name: Set vals
    command: echo 
    register: vals
  - name: Set value
    set_fact:
      vals: "{{ vals.stdout }}"
  - name: see vals
    debug:
      msg: "{{ vals }}"
  - name: Add Host
    debug:
      msg: "MISS"
    when: '(val|string) not in vals'
  - name: Add Host
    debug:
      msg: "HIT"
    when: '(val|string) in vals'