- name: Testing for EJ
  hosts: localhost
  vars:
    ip: "{{lookup('file', 'svc.txt')}}"
  tasks:
    - name: Parse test (svc)
      set_fact:
        v_ip: "{{ip | regex_search('LoadBalancer\\s+[^\\s]+\\s+([^\\s]+)\\s', '\\1')}}"
    - name: Parse test (Recovery)
      debug:
        msg: "{{v_ip}}"