- name: Testing for EJ
  hosts: localhost
  vars:
    testvar: This wi"th 'SINGLE' quotes
  
  tasks:
  - name: DEBUG
    debug:
      msg: "{{testvar}}"

  - name: Replace test
    set_fact:
      othervar: "{{testvar | string | replace(\"'\", '\"')}}"
  
  - name: DEBUG
    debug:
      msg: "{{othervar}}"