- name: Testing for EJ
  hosts: localhost
  vars:
    test: "this is  a     string"
  
  tasks:
  - name: Var testing
    debug:
      msg: "{{ test }}"

  - name: Var testing
    debug:
      msg: "{{ test.split()[3] }}"