- name: Testing for EJ
  hosts: localhost
  vars:
    tmp:
      - "8520"
      - "13974"
  tasks:
    - name: join test
      copy:
        dest: "tst.txt"
        content: "{{ ['ns '] | product(tmp) | map('join') | list | join('\n') }}"