- name: Testing for EJ
  hosts: localhost
  vars:
    testvar1: asdf
    testvar2: qwer
    testvar3: zxcv
  
  tasks:
  - name: Template testing
    template:
      src: tst.yaml.j2
      dest: tst.yaml
    