- name: Testing for EJ
  hosts: localhost
  vars:
    testvar: someval
  
  tasks:
  - name: bash test
    command: /bin/sh ./test.sh {{testvar}}
    register: output
  
  - name: DEBUG
    debug:
      msg: "{{output.stdout}}"