- name: Testing for EJ
  hosts: localhost
  vars:
    testvar:
      - name: c1
        a: c1
        b: c1
      - name: c2
        a: c1
        b: c2
      - name: c3
        a: c1
        b: c2
      - name: c4
        a: 
        b: c2
  
  tasks:
  - name: Var testing
    include_tasks: "t1.yml"
    loop: "{{ testvar }}"
    