- name: Testing for EJ
  hosts: localhost
  vars:
    tmp: "8520"
  tasks:
    - name: join test
      copy:
        dest: "tst.txt"
        content: |
          var1=1234
          var2="{{tmp}}"
          var3=09877