- name: Testing for EJ
  hosts: localhost
  vars:
    test: "name test"
  
  tasks:
  - name: Galaxy version testing
    command: ansible-galaxy install -r requirements.yml -v

  - name: Version check
    command: ansible-galaxy collection list
    register: otpt
  
  - name: Version Check
    debug:
      msg: "{{ otpt.stdout }}"