- name: Testing for EJ
  hosts: localhost
  vars:
    tstVar:
      src: tst.txt
      dest: new.txt
    extraVars:
      mode: 01777
  
  tasks:
  - name: Read first JSON file
    set_fact:
      uni: "{{ lookup('file','./tst1.json') | from_json }}"
  - name: Read second JSON file
    set_fact:
      cust: "{{ lookup('file','./tst2.json') | from_json }}"
  - name: Versions
    debug:
      msg: "Ansible: {{ ansible_version.full }} - utils: {{ lookup('community.general.collection_version', 'ansible.utils') }} - general: {{ lookup('community.general.collection_version', 'community.general') }}"
  - name: Full combine (ansible >= 2.10)
    set_fact:
      full: "{{ uni | community.general.lists_mergeby(cust, 'name', list_merge='append') }}"
    when: "ansible_version.full is version_compare('2.10', '>=')"

  - name: Full combine
    include_tasks: combine.yml
    when: "ansible_version.full is version_compare('2.10', '<')"

  - name: Full variable
    debug:
      msg: "{{ full }}"