- name: Testing for EJ
  hosts: localhost
  tasks:
    - name: Ansible Galaxy test
      command: ansible-galaxy install -r requirements.yml -v
    - name: Module Test
      avi_authmappingprofile:
        msg: test