- name: Testing for EJ
  hosts: localhost
  vars:
    tstVar:
      src: tst.txt
      dest: new.txt
    extraVars:
      mode: 01777
  
  tasks:
  - name: Before
    debug:
      msg: "{{tstVar}}"
  - name: Change
    set_fact:
      tstVar: "{{ tstVar | combine(extraVars) }}"
  - name: After
    debug:
      msg: "{{tstVar}}"
  - name: Copy
    copy:
      "{{tstVar}}"