- name: Testing for EJ
  hosts: localhost
  tasks:
    - name: Touch test
      include_tasks: "{{ item }}"
      loop:
        - t1.yml
        - t2.yml
    - name: Fail 
      fail:
        msg: This is failure text
      ignore_errors: true