-
  name: Spin up Python web server
  hosts: vm*
  tasks:
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    loop:
      - python3
      - python3-setuptools
      - python3-dev
      - build-essential
      - python3-pip
  - name: Install MySQL
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - mysql-server
      - mysql-client
  - name: Start DB
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Create DB
    mysql_db:
      name: employee_db
      state: present
  - name: Create DB User
    mysql_user:
      name: db_user
      password: Passw0rd
      priv: '*.*:ALL'
      state: present
      host: '%'
  - name: Install Flask
    pip:
      name: "{{ item }}"
      state: present
    loop:
      - flask
      - flask-mysql
  - name: Copy app code
    copy:
      src: testApp.py
      dest: /otp/app.py
  - name: Start app
    shell: FLASK_APP=/opt/app.py nohup flask run --hots=0.0.0.0 &